<?php echo $this->doctype(); ?>
<html lang="en">
    <?php echo $this->partial('layout/head.phtml', array('MetaEvent' => $MetaEvent, 'OGmetas' => $OGmetas)); //, array('MetaEvent'=>$MetaEvent)); ?>
    <body>
        <?php echo $this->partial('layout/header.phtml', array()); ?>


        <?php echo $this->partial('layout/contact_us.phtml',array('transport'=>$transport)); ?> 


        <?php echo $this->partial('layout/footer.phtml'); ?>
         <?php echo $this->partial('layout/totopJs.phtml'); ?> 
		<?php echo $this->partial('layout/faceslide.phtml'); ?> 
		<?php echo $this->partial('layout/mailcheck.phtml'); ?> 
		
		

    </body>
</html>