<?php 

?>

        <div id="home-concertq-container" class="home-concertq-container">
            <header id="filters-home-events" class="filters-home-events clearfix">
                <h4>Filters</h4>

                <section class="filter-home">
                    <a href="#" id="filter-cities"><i class="fa fa-angle-down rht"></i> Cities</a>

                    <div id="cities-tooltip" class="events-tooltip tooltip cities">
                        <div>
                            <ul>
                                <li><input type="checkbox"> <label>Arlington - TX</label></li>
                                <li><input type="checkbox"> <label>Atlanta - GA</label></li>
                                <li><input type="checkbox"> <label>Baltimore - MD</label></li>
                                <li><input type="checkbox"> <label>Chicago - IL</label></li>
                                <li><input type="checkbox"> <label>Cincinnati - OH</label></li>
                                <li><input type="checkbox"> <label>East Rutherford - NJ</label></li>
                                <li><input type="checkbox"> <label>Foxborough - MA</label></li>
                                <li><input type="checkbox"> <label>Houston - TX</label></li>
                                <li><input type="checkbox"> <label>Miami Gardens - FL</label></li>
                                <li><input type="checkbox"> <label>New Orleans - LA</label></li>
                                <li><input type="checkbox"> <label>Pasadena - CA</label></li>
                                <li><input type="checkbox"> <label>Philadelphia - PA</label></li>
                            </ul>
                        </div>
                    </div>
                </section>

                <section class="filter-home">
                    <a href="#" id="filter-cities"><i class="fa fa-angle-down rht"></i> Venues</a>

                    <div id="venues-tooltip" class="events-tooltip tooltip venues">
                        <div>
                            <ul>
                                <li><input type="checkbox"> <label>AT&amp;T Park</label></li>
                                <li><input type="checkbox"> <label>AT&amp;T Stadium</label></li>
                                <li><input type="checkbox"> <label>Citizens Bank Park</label></li>
                                <li><input type="checkbox"> <label>Georgia Dome</label></li>
                                <li><input type="checkbox"> <label>Gillette Stadium</label></li>
                                <li><input type="checkbox"> <label>Great American Ball Park</label></li>
                                <li><input type="checkbox"> <label>Investors Group Field</label></li>
                                <li><input type="checkbox"> <label>M&amp;T Bank Stadium</label></li>
                                <li><input type="checkbox"> <label>Mercedes</label></li>
                                <li><input type="checkbox"> <label>MetLife Stadium</label></li>
                                <li><input type="checkbox"> <label>Minute Maid Park</label></li>
                                <li><input type="checkbox"> <label>Rogers Centre</label></li>
                            </ul>
                        </div>
                    </div>

                </section>
            </header>

            <section id="performers-listing" class="performer-listing">
                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://i.huffpost.com/gen/1031448/thumbs/o-PAUL-MCCARTNEY-KNIGHTHOOD-facebook.jpg" alt="Paul McCartney">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Paul McCartney</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Paul McCartney sequi maxime velit dolor omnis. Sunt, totam, eum, facere temporibus possimus minus Paul McCartney assumenda quia quisquam sequi ea id Paul McCartney cumque quasi cupiditate harum inventore Paul McCartney voluptatem odio atque labore dolores modi laudantium sapiente quidem expedita quo Paul McCartney. Adipisci, asperiores, iusto.</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://musicandcelebrities.com/wp-content/uploads/2012/10/Bruno+Mars.jpg" alt="Bruno Mars">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Bruno Mars</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi, harum!</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="https://pbs.twimg.com/profile_images/442061377411108864/XfqEYJFc.jpeg" alt="Pharrell Williams">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Pharrell Williams</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem dolor sit amet, Pharrell Willams adipisicing elit. Blanditiis impedit ipsum quae repellat! Sed, Pharrell Willams illo architecto quis esse Pharrell Willams perspiciatis adipisci.</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://www.outune.net/wp-content/images/2013/11/aerosmith-2013-468x301.jpg" alt="Aerosmith">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Aerosmith</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus repudiandae inventore iste Aerosmith nobis. Cum, dolorum optio ipsam saepe ipsa sequi consequuntur Aerosmith. Nostrum, eos fugiat quaerat blanditiis Aerosmith odit soluta iste ullam?</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://media.mwcradio.com/mimesis/2014-01/31/tmpe2rZSU_jpg_475x310_q85.jpg" alt="Luke Bryan">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Luke Bryan</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur Luke Bryan elit. Placeat, explicabo ex veritatis.</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://www.feelguide.com/wp-content/uploads/2013/10/TheresaCaputo.jpg" alt="Theresa Caputo">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Theresa Caputo</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, optio Theresa Caputo quisquam nesciunt voluptates possimus ipsum quo earum maxime of Theresa Caputo.</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://cdn9.staztic.com/app/a/2108/2108907/lee-brice-live-wallpaper-316265-2-s-307x512.jpg" alt="Lee Brice">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Lee Brice</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat, fugit, molestias, saepe, accusantium laboriosam sit obcaecati incidunt necessitatibus sapiente aliquid cum quos.</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://wac.450f.edgecastcdn.net/80450F/theboombox.com/files/2013/09/Justin-Timberlake.jpg" alt="Justin Timberlake">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Justin Timberlake</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis, in sit cum eveniet nesciunt quam quidem neque cumque molestias ipsa magnam fuga cupiditate dolorum iusto nostrum fugit facere vero facilis nobis explicabo? Ullam, exercitationem!</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>

                <article class="performer-box">
                    <header>
                        <a href="#">
                            <img src="http://1.bp.blogspot.com/-keoLXXdpd9Q/UidnsS_mHGI/AAAAAAAAB2Q/ClgIFI4JQRI/s1600/beyonce+%281%29.jpg" alt="Beyonce" title="Beyonce">
                            <i class="fa fa-eject"></i>
                        </a>
                        <h2 class="performer-title"><a href="#">Beyonce</a></h2>
                    </header>

                    <section>
                        <abbr class="date"><strong>Feb 15</strong>, 2014 08:00 pm</abbr>
                        <span class="location"><strong>The Chelsea</strong>, Las Vegas, NV</span>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa, accusamus tempore officiis ipsa unde facilis voluptatum veniam odio eum. Odio, quae tempore soluta repellat voluptates totam magnam. Ea, maiores, nostrum dolor nam earum ducimus dignissimos inventore cum ipsam ratione nihil vel itaque?</p>
                    </section>

                    <footer><a href="#" class="c-button see-tickets">See Tickets<i class="fa fa-angle-right"></i></a></footer>
                </article>
            </section>
        </div>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
        <script src="js/jscrollpane.min.js" type="text/javascript"></script>
        <script src="js/isotope.min.js" type="text/javascript"></script>
        <script src="js/infinitescroll.min.js" type="text/javascript"></script>
        <script src="js/concertq.js" type="text/javascript"></script>
    </body>