<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// start session
$some_name = session_name("some_name");
session_set_cookie_params(0, '/', '.concertticketsq.com');
session_start();
// kill the session
session_destroy();
$site_url=$this->url('www',array());


// redirect back to website home
echo $this->headMeta()->appendHttpEquiv('Refresh', '0;URL='.$site_url);