<div id="mainBody">

    <div class="mainPanel">

        <div id="content" class="mainContent">

            <h1 class="title_event" style="font-size:25px">Learn More About ConcertTicketsQ.com</h1>
            <div class="pagesContainer">
                <div class="pagesNav">
                    <div class="inner">
                        <a href="<?php echo $this->url('www/about', array()); ?>" alt="Read About ConcertTicketsQ.com" title="Read About ConcertticketsQ.com" >About Us</a>

                        <a alt="Contact Tickets.com" title="Contact ConcertticketsQ.com" href="<?php echo $this->url('www/contact', array()); ?>">Contact Us</a>

                        <a href="<?php echo $this->url('www/help', array()); ?>" alt="Read the ConcertticketsQ.com Help" title="Read the ConcertticketsQ.com Help" class="last ">Help</a>

                    </div>
                    <div class="inner">
                          <a href="https://www.facebook.com/concertticketsq" alt="Follow us on Facebook" title="Follow us on Facebook">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-facebook.png"></span></a>

                        <a href="https://twitter.com/Concertticketsq" alt="Follow us on Twitter" title="Follow us on Twitter">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-twitter.png"></span></a>

                        <a href="https://plus.google.com/102808484460614098000" alt="Follow us on Google plus" title="Follow us on Google plus">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-googleplus.png"></span></a>

                        <a href="http://www.pinterest.com/concertticketsq/" alt="Follow us on Pinterest" title="Follow us on Pinterest">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-pinterest.png"></span></a>

                    </div>
                    <div class="inner-facebook">
                        <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fconcertticketsq&amp;width&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false&amp;appId=517712165003999" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:290px;width:200px" allowTransparency="true"></iframe>
                    </div>


                </div>
                <div class="pagesContent">
                    <div class="copyArticle">
                        <br><br>

                        <div class="imageContainer right">
                            <img src="<?php echo $this->basePath(); ?>/img/about.jpg"><br><br>
                            
                        </div>
                        <h1 style="font-size:16px">Concert Tickets Q</h1>
                        <p>We have an extended experience in offering tickets for major events that appear around the country. When your best performer is hitting the stage somewhere in your city, you can’t find better than this website to get your tickets.</p><br>

                        <h1 style="font-size:16px">What We Do</h1>

                        <p>concertticketsq.com is a hub of cheap tickets for all major music events that take place over USA. We are offering you the key to enjoy yourself and join the other fans that attend all live events appearing in your city. This could be your ultimate source of concert tickets. The prices we are listing here are significantly cheap and reasonable. Even when you think that an event is sold out, and you searched in different places but can’t locate your tickets, you can browse through our website and still can find your tickets and profit of the considerably low prices we list.</p><br>



                        <p>When you can’t locate tickets of an event, we’ll be more than happy to hear from you and we’ll see if there still something we can do to serve you. Legions of customers have already chosen concertticketsq.com as a source to purchase tickets for all hot events they are interested in including concerts of legends and famous performers, or any of the festivals taking place around the country all along the year.</p><br>

                        <p>We’re more than glad to make business with you, and when you have any questions, we appreciate getting contacted by our customers, or prospect ones, or just those that seek clarification about tickets sold on our site. We do our best to improve your experience as a user of our website, and we’re open to hear your suggestions and recommendations.</p><br>

                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="clear"></div>
        </div>
    </div>
    <!--<div align="left" class="ticketsanaheim_box_cit_bot-page">
       

        <div class="footer-container">

            <div class="foot">

                <div class="foot_link">
                    <a href="http://www.ticketsanaheim.org/aboutus.php" style="text-decoration:none;" title="About Us">About Us</a> | <a href="http://www.ticketsanaheim.org/contact.php" style="text-decoration: none;" title="Contact Us">Contact Us</a> | <a href="http://www.ticketsanaheim.org/help.php" style="text-decoration: none;" title="Help">Help</a> <br>
                    <h4> Concert Tickets Q</h4>
                    Copyright &copy; 2014. concerticketsq.com.
                    All Rights Reserved.

                </div>
                <div class="foot_social">
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-facebook.png" class="img_facebook" title="facebook"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-twitter.png" class="img_facebook" title="twitter"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-googleplus.png" class="img_facebook" title="googleplus"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-pinterest.png" class="img_facebook" title="pinterest"></a>
                </div>
            </div>
        </div>

    </div>-->
</div>