
<div id="ct-filters" class="ct-filters">
                <section>
                    <a href="#" id="refresh-filters" class="refresh-filters fa fa-refresh rht"></a>

                    <strong># of tickets:</strong>
                    <select id="number-tickets">
                        <option value="Any" class="list" selected="selected">Any</option>
                        <option value="1" class="list">1</option>
                        
                    </select>
                </section>

                <section>
                    <label><i class="fa fa-dollar"></i> 
                        <input type="text" id="min-price-tickets" value="49" />
                    </label>
                    <div id="range-price" class="range-price" data-minprice="9" data-maxprice="895"></div>
                    <label><i class="fa fa-dollar"></i> 
                        <input type="text" id="max-price-tickets" value="325" />
                    </label>
                </section>

                <section>
                    <section class="filter-list">
                        <a href="#" id="filter-sections"><i class="fa fa-chevron-down rht"></i> Sections / Areas</a>
                        <div class="tickets-tooltip tooltip sections-areas">
                            <b class="spr"></b>
                            <div>
                                <ul class="jscroll">
                                    <li><input type="checkbox" id="106 BASELINE" value="106 BASELINE" > <label for="106 BASELINE">106 BASELINE</label></li>
                                    
                                </ul>
                            </div>
                        </div>
                    </section>

                    <section class="filter-list">
                        <a href="#" id="filter-brokers"><i class="fa fa-chevron-down rht"></i> Brokers</a>

                        <div class="tickets-tooltip tooltip brokers">
                            <div>
                                <ul>
                                    <li><input value="AceTickets" name="AceTickets" id="AceTickets" type="checkbox"> <label for="AceTickets">AceTickets</label></li>
                                    
                                </ul>
                            </div>
                        </div>
                    </section>
                </section>
            </div>