<head>
        <meta charset="utf-8">
        <meta name="description" content=" Buy Venue Event concert City tickets at concertq.com.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" content="">
        <title>  </title>
        <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/dest/concertq.min.css">
    </head>
    <body>
        
        <header id="concertq-header" class="concertq-header clearfix">
            <a href="#" id="concertq-logo" class="concertq-logo"><img src="<?php echo $this->basePath()?>/img/concertq-logo.png" width="94" height="24" alt="ConcertQ" class="concertq-logo"></a>

            <div id="concertq-search" class="concertq-search">
                <input type="text" id="concertq-search-field" onkeyup="search();" class="concertq-search-field" name="concertq-search-field" placeholder="Search concert events...">
                <span class="fa fa-search send-search" id="send-search" title="Search"></span>
            </div>

            <nav id="about-concertq" class="about-concertq">
                <ul>
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Contact us</a></li>
                    <li><a href="#">Help</a></li>
                </ul>
            </nav>
        </header>
   
