<section class="filter-home">
    <a href="#" id="filter-cities"><i class="fa fa-angle-down rht"></i> Top Performers</a>
    <div id="performers-tooltip" class="events-tooltip tooltip cities">
        <div>
            <form id='form_filter_performers' method="post">  
                <ul>
                    <?php foreach ($topperformers as $topperformer) : ?>
                        <li><input class="limit_check_p" type="checkbox" onclick="showValues();" id='performer:<?php echo $topperformer->get_id(); ?>' value='<?php echo $topperformer->get_id(); ?>'><a href="http://<?php echo $topperformer->get_link_dash(); ?>.concertticketsq.com"> <label class="space"><?php echo $topperformer->get_name(); ?> </label> </a></li>
                    <?php endforeach; ?>

                </ul>
            </form>
        </div>
    </div>
</section>


<section class="filter-home">
    <a href="#" id="filter-cities"><i class="fa fa-angle-down rht"></i> Cities</a>
    <div id="cities-tooltip" class="events-tooltip tooltip citiess">
        <div>
            <form id='form_filter_cities' method="post">
                <ul>
                    <?php foreach ($topcities as $topcity) : ?>
                        <li><input class="limit_check_c" onclick="showValues();" id='city:<?php echo $topcity->get_id(); ?>' value='<?php echo $topcity->get_id(); ?>' type="checkbox"  > <a href="<?php
                            
                            echo $this->url('www/cityPage', array(
                                'action' => 'city',
                                'city' => $topcity->get_link_dash()
                                ));
                            ?>"> <label class="space"><?php echo $topcity->get_name(); ?> </label> </a></li>
                                                                                                                                                                                         <?php endforeach; ?>
                </ul>
            </form>
        </div>
    </div>
</section>




<section class="filter-home">
    <a href="#" id="filter-cities"><i class="fa fa-angle-down rht"></i> Venues</a>

    <div id="venues-tooltip" class="events-tooltip tooltip cities">
        <div>
            <form id='form_filter_venues' method="post">  
                <ul>
                    <?php foreach ($topvenues as $topvenue) : ?>         
                        <li><input class="limit_check_v squaredThree" onclick="showValuesvenue();" id='venue:<?php echo $topvenue->getVenue()->get_id(); ?>' value='<?php echo $topvenue->getVenue()->get_id(); ?>' type="checkbox" > <label class="space"><?php echo $topvenue->getVenue()->get_name(); ?></label></li>
                        <?php endforeach; ?>
                </ul>
            </form>
        </div>
    </div>
</section>


