<div id="mainBody">

    <div class="mainPanel">

        <div id="content" class="mainContent">

            <h1 class="title_event" style="font-size:25px">Help ConcertTicketsQ.com</h1>
            <div class="pagesContainer">
                <div class="pagesNav">
                    <div class="inner">

                         <a href="<?php echo $this->url('www/about', array()); ?>" alt="Read About ConcertTicketsQ.com" title="Read About ConcertticketsQ.com" >About Us</a>

                        <a alt="Contact Tickets.com" title="Contact ConcertticketsQ.com" href="<?php echo $this->url('www/contact', array()); ?>">Contact Us</a>

                        <a href="<?php echo $this->url('www/help', array()); ?>" alt="Read the ConcertticketsQ.com Help" title="Read the ConcertticketsQ.com Help" class="last ">Help</a>

                    </div>
                    <div class="inner">
                          <a href="https://www.facebook.com/concertticketsq" alt="Follow us on Facebook" title="Follow us on Facebook">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-facebook.png"></span></a>

                        <a href="https://twitter.com/Concertticketsq" alt="Follow us on Twitter" title="Follow us on Twitter">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-twitter.png"></span></a>

                        <a href="https://plus.google.com/102808484460614098000" alt="Follow us on Google plus" title="Follow us on Google plus">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-googleplus.png"></span></a>

                        <a href="http://www.pinterest.com/concertticketsq/" alt="Follow us on Pinterest" title="Follow us on Pinterest">Follow us on<span><img class="about-img" src="<?php echo $this->basePath(); ?>/img/32-pinterest.png"></span></a>

                    </div>
                    <div class="inner-facebook">
                        <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fconcertticketsq&amp;width&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=false&amp;appId=517712165003999" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:290px;width:200px" allowTransparency="true"></iframe>
                    </div>


                </div>
                <div class="pagesContent">
                    <div class="copyArticle">
                        <br><br>

                        <div class="imageContainer">
                            <img src="<?php echo $this->basePath(); ?>/img/theatre.jpg"><br><br>
                            
                        </div>
                        <h1 style="font-size:16px">Concert Tickets Q</h1><br>
                        <p>As you can see, our website is dedicated to providing concerts tickets for all main performers. On the main page you can see pictures of hot performers, so you can pick what you like and click the name link or the red icon “See Tickets” appearing down the image. As you scroll down the page, more events will appear to you. In the left side of the page, you can see “Trending” performers that mean the hot ones at the present time.</p> <br>
                        <p>When you make your choice, you can move to the next step to see the events listed for your performer. There you can find details about the events including the name, date, and location where the concert is taking place. The results are not all shown, but you have to click on “Show more” if you want to see more events and locations.</p>
                        <br>

                        <p>In the left side, you can narrow your search by checking the city you are interested in. Or you can also choose related events if you want to move to see events of other performers. And when you are done and decided what tickets you want to buy, you can click “See Tickets” appearing in the far right and move on to the next step.<p><br>
                        <p>After moving forward to buy your tickets, you can see more details about tickets you want to purchase including section, row, quantity, and price. You can also see a map showing location of your seats so you can have an idea where you’ll sit. There’s also another direction map showing details of how to reach the venue where the concert is held. Now after, you have all the details you want, you can move to the final process of paying for your tickets and guarantee your attendance.</p> <br>

                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="clear"></div>
        </div>
    </div>
    <!--<div align="left" class="ticketsanaheim_box_cit_bot-page">
        

        <div class="footer-container">

            <div class="foot">

                <div class="foot_link">
                    <a href="http://www.ticketsanaheim.org/aboutus.php" style="text-decoration:none;" title="About Us">About Us</a> | <a href="http://www.ticketsanaheim.org/contact.php" style="text-decoration: none;" title="Contact Us">Contact Us</a> | <a href="http://www.ticketsanaheim.org/help.php" style="text-decoration: none;" title="Help">Help</a> <br>
                    <h4> Concert Tickets</h4>
                    Copyright &copy; 2014. concertickets.com.
                    All Rights Reserved.

                </div>
                <div class="foot_social">
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-facebook.png" class="img_facebook" title="facebook"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-twitter.png" class="img_facebook" title="twitter"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-googleplus.png" class="img_facebook" title="googleplus"></a>
                    <a href=""><img src="<?php echo $this->basePath(); ?>/img/32-pinterest.png" class="img_facebook" title="pinterest"></a>
                </div>
            </div>
        </div>

    </div>-->
</div>