<table id="table-listing" class="table-listing" cellspacing="0" cellpadding="0">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Event</th>
                                <th>Location</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="dtstart datevent" title="2014-02-19T19:30">
                                    <abbr class="value-title">
                                        <strong>Feb 19</strong>
                                        <span>Wed 7:30 PM</span>
                                    </abbr>
                                </td>
                                <td class="event-summary">
                                    <a href="#">
                                        <span class="summary" title="Paul McCartney">Paul McCartney</span>
                                    </a>
                                </td>
                                <td class="venue">
                                    <span class="fn org">Staples Center</span> -
                                    <span class="adr">
                                        <span class="locality">Los Angeles</span>,
                                        <span class="region">CA</span>
                                    </span>
                                </td>
                                <td class="action">
                                    <a href="javascript:void(0)" class="see-action c-button"><span>See Tickets</span> <i class="fa fa-angle-right"></i></a>
                                </td>
                            </tr> 
                        </tbody>
                    </table>