<aside id="filter-performer-events" class="filter-performer-events">
    				<div class="c-filter">
                        <header class="clearfix">
                            <i class="fa fa-plus rht"></i>
                            <h4>Cities</h4>
                        </header>
                        <ul>
                            <li>
                                <input type="checkbox" id="check-Denver">
                                <label>Denver - CO</label>
                            </li>
                            
                        </ul>
                    </div>

                    <div class="c-filter">
                        <header class="clearfix">
                            <i class="fa fa-minus rht"></i>
                            <h4>Venues</h4>
                        </header>
                        <ul class="hide">
                            <li>
                                <input type="checkbox" id="check-AT">
                                <label>AT&T Center</label>
                            </li>
                            
                        </ul>
                    </div>


                    <div class="c-filter">
                        <header class="clearfix">
                            <i class="fa fa-minus rht"></i>
                            <h4>Related Events</h4>
                        </header>
                        <ul class="hide">
                            <li><a href="#">Paul McCartney Perth</a></li>
                            
                        </ul>
                    </div>
        		</aside>