<header id="performer-presentation" class="performer-presentation c-wrapper">
                <div class="performer-image">
                    <img src="http://www.radiomilwaukee.org/sites/default/files/images/story/485918_10151575816248313_124779029_n.jpg" alt="Paul McCartney" title="Paul McCartney">
                </div>

                <div class="performer-information">
                    <ul id="breadcrumbs" class="breadcrumbs">
                        <li><a href="#">Concertq</a></li>
                        <li><i class="fa fa-angle-right"></i></li>
                        <li><a href="#" class="current">Paul McCartney events</a></li>
                    </ul>

                    <h1>Paul McCartney Events</h1>
                    <p>Get ready for Paul McCartney, all the way live. Paul McCartney is playing this year in many cities. Buy premium Paul McCartney tickets and experience the thrill of a live concert with Paul McCartney at affordable prices.</p>

                    <span>63 Events found available in this time</span>
                </div>
        	</header>