<?php
if ($ajax === 1) {
    echo $this->partial('layout/search_events.phtml', array('eventsK' => $eventsK, 'offset' => $offset, 'eventsCount' => $eventsCount, 'ajax' => $ajax, 'search' => $search));
    exit;
}
?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <?php echo $this->partial('layout/head.phtml'); //, array('MetaEvent'=>$MetaEvent)); ?>
    <body>
        <?php echo $this->partial('layout/header.phtml', array()); ?>
        <div class="container">
            <section id="event-concertq-container" class="event-concertq-container">
                <header id="filters-home-events" class="filters-home-events clearfix">
                    <h4>Filters</h4>

                    <?php echo $this->partial('layout/filtercities_1.phtml'); ?> 

                </header>

                <section id="performer-events" class="performer-events c-wrapper">
                    <aside id="filter-performer-events" class="filter-performer-events">


                        <?php //echo $this->partial('layout/cities_venue_filter.phtml', array('groupvenues' => $groupvenues)); ?>

                        <?php // echo $this->partial('layout/cities_related_city.phtml', array('relatedPerformers' => $relatedPerformers));  ?>


                    </aside>
                    <div id="performer-events-listing-search" class="performer-events-listing-search">
                        <?php echo $this->partial('layout/search_events.phtml', array('eventsK' => $eventsK, 'offset' => $offset, 'eventsCount' => $eventsCount, 'ajax' => $ajax, 'search' => $search)); ?>
                       
                    </div>




                </section>

            </section>

            <?php echo $this->partial('layout/footer.phtml'); ?>
            <?php echo $this->partial('layout/search_partialJS.phtml'); ?>
               <?php echo $this->partial('layout/partialjs'); ?>
        </div> <!-- /container -->
        <?php // echo $this->inlineScript()  ?>
    </body>
</html>



