        <script>
            /****** To top*********/
window.onload=function(){
            $('#toTop').hide();
        };
        $(window).scroll(function(){
        if ($(this).scrollTop() > 100) {
            $('#toTop').fadeIn();
        } else {
            $('#toTop').fadeOut();
        }
    });

            $('#toTop').on("click", function () {
    var percentageToScroll = 100;
    var percentage = percentageToScroll / 100;
    var height = $(document).scrollTop();
    var scrollAmount = height * (1 - percentage);

    
    $('html,body').animate({
        scrollTop: scrollAmount
    }, 'slow', function () {
        
    });

});
/****** end To top*********/

        </script>

      